AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda execution role
Parameters:
  ProjectName:
    Type: String
  Env:
    Type: String
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-${Env}-lambda-role
      Path: '/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - cloudformation.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument: {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": "*",
                "Resource": "*"
              }
            ]
          }
Outputs:
  RoleArn:
    Description: ARN of the lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn
