AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda execution role
Outputs:
  RoleArn:
    Description: ARN of the lambda execution role
    Value:
      'Fn::GetAtt':
        - LambdaExecutionRole
        - Arn
Parameters:
  Env:
    Type: String
  ProjectName:
    Type: String
Resources:
  LambdaExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Action: 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
              - cloudformation.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action: '*'
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: root
      RoleName:
        'Fn::Sub': '${ProjectName}-${Env}-lambda-role'
    Type: 'AWS::IAM::Role'

